---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - team: team-green
                - team: team-blue
          - git:
              directories:
                - path: monitoring-appset/*
              repoURL: https://github.com/vixus0/gitops-examples
              revision: HEAD
  goTemplate: true
  template:
    metadata:
      name: "{{ .team }}-{{ .path.basename }}"
    spec:
      project: team-monitoring
      source:
        repoURL: https://github.com/vixus0/gitops-examples
        targetRevision: HEAD
        path: "{{ .path.path }}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        name: in-cluster
        namespace: "{{ .team }}" # this is dangerous!
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
