apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: first-gitops-app
  namespace: argocd
spec:
  destination:
    namespace: first-gitops-app
    name: in-cluster
  project: default
  source:
    path: first-gitops-app
    repoURL: https://github.com/vixus0/gitops-examples
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
